baseURL = 'https://paperwhite.nickolaskraus.io'
languageCode = 'en-US'
title = 'Paperwhite'
theme = 'paperwhite'

[markup]
  [markup.highlight]
    # Disable syntax highlighting.
    noClasses = false

# Google Analytics measurement ID (Google Analytics 4)
# [services]
#   [services.googleAnalytics]
#     id = 'G-MEASUREMENT_ID'
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Docs'
pageRef = '/docs'
weight = 20

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
