baseURL = 'https://paperwhite.nickolaskraus.io'
languageCode = 'en-US'
title = 'Paperwhite'
description = '''
A minimalist Hugo theme using Tailwind CSS and vanilla JavaScript
'''
theme = 'paperwhite'

[markup]
  [markup.highlight]
    # Disable syntax highlighting.
    noClasses = false

# Google Analytics measurement ID (Google Analytics 4)
# [services]
#   [services.googleAnalytics]
#     id = 'G-MEASUREMENT_ID'

[params]

  author = 'Nickolas Kraus'

  [params.seo]
    image = 'logo.png'
    twitter_card = 'summary'
    twitter_site = '@nickolashkraus'
    twitter_creator = '@nickolashkraus'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Docs'
pageRef = '/docs'
weight = 20

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
